-- Permit the two binary export formats generated by the report workspace.
update storage.buckets
set allowed_mime_types = array[
  'application/json',
  'text/markdown',
  'text/html',
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
]
where id = 'analysis-exports';
